2021-01-07 21:00:42,448 INFO: GameX startup [in C:\Users\laure\OneDrive\Bureaublad\GameY\app\__init__.py:44]
2021-01-07 21:00:51,550 ERROR: Exception on /edit_profile [GET] [in c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\laure\OneDrive\Bureaublad\GameY\app\routes.py", line 50, in edit_profile
    form.about_me.data = current_user.about_me
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'about_me'
2021-01-07 21:05:48,944 ERROR: Exception on /edit_profile [GET] [in c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\laure\OneDrive\Bureaublad\GameY\app\routes.py", line 50, in edit_profile
    form.about_me.data = current_user.about_me
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'about_me'
2021-01-07 21:10:53,459 INFO: GameX startup [in C:\Users\laure\OneDrive\Bureaublad\GameY\app\__init__.py:44]
2021-01-07 21:10:58,216 ERROR: Exception on /edit_profile [GET] [in c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\laure\OneDrive\Bureaublad\GameY\app\routes.py", line 50, in edit_profile
    form.about_me.data = current_user.about_me
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'about_me'
2021-01-07 21:15:39,536 INFO: GameX startup [in C:\Users\laure\OneDrive\Bureaublad\GameY\app\__init__.py:44]
2021-01-07 21:15:50,812 INFO: GameX startup [in C:\Users\laure\OneDrive\Bureaublad\GameY\app\__init__.py:44]
2021-01-07 21:19:26,189 INFO: GameX startup [in C:\Users\laure\OneDrive\Bureaublad\GameY\app\__init__.py:44]
2021-01-07 21:22:46,151 INFO: GameX startup [in C:\Users\laure\OneDrive\Bureaublad\GameY\app\__init__.py:44]
2021-01-07 21:22:50,663 ERROR: Exception on /edit_profile [GET] [in c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\laure\OneDrive\Bureaublad\GameY\app\routes.py", line 51, in edit_profile
    form.about_me.data = current_user.about_me
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'about_me'
2021-01-07 21:23:00,671 ERROR: Exception on /edit_profile [GET] [in c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\laure\OneDrive\Bureaublad\GameY\app\routes.py", line 51, in edit_profile
    form.about_me.data = current_user.about_me
  File "c:\users\laure\onedrive\bureaublad\gamey\venv\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'about_me'
